server:
  port: 9012
spring:
  application:
    name: tensquare-web
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-gathering: # 活动
      path: /gathering/** # 配置请求URL的请求规则
      serviceId: tensquare-gathering # 指定Eureka注册中心中的服务id
    tensquare-article: # 文章
      path: /article/** # 配置请求URL的请求规则
      serviceId: tensquare-article # 指定Eureka注册中心中的服务id
    tensquare-base: # 基础
      path: /base/** # 配置请求URL的请求规则
      serviceId: tensquare-base # 指定Eureka注册中心中的服务id
    tensquare-friend: #交友
      path: /friend/** # 配置请求URL的请求规则
      serviceId: tensquare-friend # 指定Eureka注册中心中的服务id
    tensquare-qa: #问答
      path: /qa/** # 配置请求URL的请求规则
      serviceId: tensquare-qa # 指定Eureka注册中心中的服务id
    tensquare-recruit: #招聘
      path: /recruit/** # 配置请求URL的请求规则
      serviceId: tensquare-recruit # 指定Eureka注册中心中的服务id
    tensquare-spit: # 吐槽
      path: /spit/** # 配置请求URL的请求规则
      serviceId: tensquare-spit # 指定Eureka注册中心中的服务id
    tensquare-user: # 用户
      path: /user/** # 配置请求URL的请求规则
      serviceId: tensquare-user   # 指定Eureka注册中心中的服务id

